apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ipow6rlik-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ipow6rlik-go 
  name: ipow6rlik-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ipow6rlik-go 
