apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ipow6rlik-go 
  janus-idp.io/tekton: ipow6rlik-go
  backstage.io/kubernetes-id: ipow6rlik-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ipow6rlik-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml